apiVersion: v1
kind: ConfigMap
metadata:
  name: pingapp-configmap
  labels:
    app: pingapp-configmap
data:
  DEVELOPER: Laura
  CONFIG_LOCATION: /mydata/config.json 

---
apiVersion: v1
kind: Service
metadata:
  name: pingapp
  labels:
    app: pingapp
  annotations:
    dev.okteto.com/auto-ingress: "private"  
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4567
  selector:
   app: pingapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp-deployment
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:2.1.0
        ports:
        - containerPort: 4567
        envFrom:
          - configMapRef:
              name: pingapp-configmap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingapp
    annotations:
      dev.okteto.com/generate-host: "true"
      dev.okteto.com/private: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: pingapp
          servicePort: 8080
        path: /
